export {Home}  from "../pages/Home"
export {Header} from "./Header/Header"
export {TrendGameCard} from "./TrendGameCard/TrendGameCard"
export {NavMenu} from "./NavMenu/NavMenu"
export{SwiperItem} from "./Swiper/SwiperItem"
export {Trends} from "./Trends/Trends"
export {DiscountGames} from "./DiscountGames"
export {SwiperCard} from "./SwiperCard/SwiperCard"